const gradientsByType = {
    normal: "bg-gradient-to-b from-normal to-white",
    fighting: "bg-gradient-to-b from-fighting to-white",
    fire: "bg-gradient-to-b from-fire to-white",
    water: "bg-gradient-to-b from-water to-white",
    flying: "bg-gradient-to-b from-flying to-white",
    grass: "bg-gradient-to-b from-grass to-white",
    poison: "bg-gradient-to-b from-poison to-white",
    electric: "bg-gradient-to-b from-electric to-white",
    ground: "bg-gradient-to-b from-ground to-white",
    psychic: "bg-gradient-to-b from-psychic to-white",
    rock: "bg-gradient-to-b from-rock to-white",
    ice: "bg-gradient-to-b from-ice to-white",
    bug: "bg-gradient-to-b from-bug to-white",
    dragon: "bg-gradient-to-b from-dragon to-white",
    ghost: "bg-gradient-to-b from-ghost to-white",
    dark: "bg-gradient-to-b from-dark to-white",
    steel: "bg-gradient-to-b from-steel to-white",
    fairy: "bg-gradient-to-b from-fairy to-white",
}

const borderByTypes = {
    normal: "border-8 border-normal",
    fighting: "border-8 border-fighting",
    fire: "border-8 border-fire",
    water: "border-8 border-water",
    flying: "border-8 border-flying",
    grass: "border-8 border-grass",
    poison: "border-8 border-poison",
    electric: "border-8 border-electric",
    ground: "border-8 border-ground",
    psychic: "border-8 border-psychic",
    rock: "border-8 border-rock",
    ice: "border-8 border-ice",
    bug: "border-8 border-bug",
    dragon: "border-8 border-dragon",
    ghost: "border-8 border-ghost",
    dark: "border-8 border-dark",
    steel: "border-8 border-steel",
    fairy: "border-8 border-fairy",
}

const bgByType = {
    normal: "bg-normal",
    fighting: "bg-fighting",
    fire: "bg-fire",
    water: "bg-water",
    flying: "bg-flying",
    grass: "bg-grass",
    poison: "bg-poison",
    electric: "bg-electric",
    ground: "bg-ground",
    psychic: "bg-psychic",
    rock: "bg-rock",
    ice: "bg-ice",
    bug: "bg-bug",
    dragon: "bg-dragon",
    ghost: "bg-ghost",
    dark: "bg-dark",
    steel: "bg-steel",
    fairy: "bg-fairy",
}

export {gradientsByType, borderByTypes, bgByType}